### ISSUE TITLE
July 2020 review

### ISSUE THREAD

**Issue by linusonline** [AMSP-04/NETN-METOC#10]
Issues found during review:

- Semantics of many elements can be improved.
- GeoReferenceVariant does not have alternatives for Circle or Path, even though the discriminant Enum type does (which is not used for anything else). **EDIT:** Suggest adding alternative for Circle with data type GeodeticCircle.
- NETNGeoObjectReference of GeoReferenceVariant should refer to Point, Path or Area. (Not to “leaf classes”, as that excludes area and includes volume instead.)
- SeaStateEnum16 values have wrong naming convention. Should use CamelCase instead of Upper_snake_case.
- Inconsistent naming and typing of Enum types. Should Enum type names include bit size? Should we, in general, use 16 or 32 bits for enums? **EDIT:** Enum type names should indeed include bit size. Suggest correcting the names, but not changing bit size of any types now.
- IceTypeEnum has only one value: 0 (None).
- ~~Swell and Wave attributes of WaterSurface have identical data types and semantics. Should probably remove Swell.~~

**Comment by lofstrandbjorn** [comment]
Swell needs to remain. Waves can move in one direction and Swell in another.

**Comment by lofstrandbjorn** [comment]
Please Fix SeaStateEnum16  naming

**Comment by linusonline** [comment]
> 
> 
> Swell needs to remain. Waves can move in one direction and Swell in another.

Ah, I misunderstood, then.
