### ISSUE TITLE
Grammar and spelling corrections

### ISSUE THREAD

**Issue by sam-d-hall** [AMSP-04/NETN-METOC#9]
README.md:
- Update scope section to match NETN-METOC.md scope section by removing the detail that overlaps with the overview section.

NETN-METOC.md:
- "The Weather object class represent..." to "The Weather object class represents..."
- "environmetn" to "environment"
- "tempereature" to "temperature"
- "moste" to "most"
- "thinckness" to "thickness"
- "variouse" to "various"
- "sublasses" to "subclasses"
- "milibar" to "millibar"
- "desity" to "density"

NETN-METOC.xml
- BarometricPressure semantics "milibar" to "millibar"
- Snow semantics "desity" to "density"
- Tropopause Layer attribute semantics "thinckness" to "thickness"
- Response semantics "resonse" to "response"
- AtmosphericPressureFloat32 "mesured" to "measured" and "milibar" to "millibar"
- SurfaceMoistureEnum16 "ot" to "of"
- SeaStateEnum16 "sate" to "state"
- GeoReferenceVariant Point "eath" to "earth"

**Comment by lofstrandbjorn** [comment]
README.md:

Update scope section to match NETN-METOC.md scope section by removing the detail that overlaps with the overview section.

- Done
